package com.example.demo.Controller;

import com.example.demo.Model.Plane;
import com.example.demo.Repository.PlaneRepository;
import com.example.demo.Service.PlaneService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class PlaneController {
    final PlaneService planeService;

    @Autowired
    public PlaneController(PlaneService planeService){
        this.planeService = planeService;
    }

//    @Autowired // This means to get the bean called planeRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private PlaneRepository planeRepository;




    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewPlane (@RequestParam String model
            , @RequestParam int capacity,@RequestParam String manufacturer, @RequestParam int yearOfManufacture) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        System.err.println("model: " + model);
        System.err.println("capacity: " + capacity);
        Plane n = new Plane(model, capacity, manufacturer,yearOfManufacture );
//        planeRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Plane> getAllPlane() {
        // This returns a JSON or XML with the planes
        return planeService.getAllPlanes();
    }
}
